### ISSUE TITLE
I am having trouble downloading the dataset

### ISSUE THREAD

**Issue by donghwijung** [ignaciotb/UWExploration#44]
Hi, thank you for sharing this awesome code.

I have a question about downloading the dataset.

When I tried to download the dataset from git large file storage, I got errors like this:

`
fetch: Fetching reference refs/heads/master
`
`
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
`
`
error: failed to fetch some objects from 'https://github.com/ignaciotb/UWExploration.git/info/lfs'
`

I typed the `git lfs fetch` in the root directory.

Could you check it for me? or any suggestion to download the dataset?

Thank you :)

**Comment by ignaciotb** [comment]
Hi, try cloning the full repository directly

**Comment by donghwijung** [comment]
Thank you for the answer

When I tried to clone the repository directly, I got errors like this

`
Downloading utils/uw_tests/datasets/ripples/mbes_pings.cereal (1.3 GB)
`
`
Error downloading object: utils/uw_tests/datasets/ripples/mbes_pings.cereal (239110a): Smudge error: Error downloading 
`
`
utils/uw_tests/datasets/ripples/mbes_pings.cereal (239110acadad7783d3fdde1a1baffff01ff4bf769f6393bafce08048016b8f7f): 
`
`
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data 
packs to restore access.
`
`
Errors logged to '/home/jungdonghwi@ad.ufl.edu/Downloads/UWExploration/.git/lfs/logs/20231031T161112.663884972.log'.
`
`
Use git lfs logs last to view the log.
`
`
error: external filter 'git-lfs filter-process' failed
`
`
fatal: utils/uw_tests/datasets/ripples/mbes_pings.cereal: smudge filter lfs failed
`
`
warning: Clone succeeded, but checkout failed.
`
`
You can inspect what was checked out with 'git status'
`
`
and retry with 'git restore --source=HEAD :/'
`

To follow the instructions in 'Basic demo with one AUV', the file `utils/uw_tests/datasets/ripples/mbes_pings.cereal` was necessary which I couldn't download

Is there any way to download the data files including 'ripples' and 'antarctica19_7'?

**Comment by hhsupremehh627** [comment]
> Thank you for the answer
> 
> When I tried to clone the repository directly, I got errors like this
> 
> `Downloading utils/uw_tests/datasets/ripples/mbes_pings.cereal (1.3 GB)` `Error downloading object: utils/uw_tests/datasets/ripples/mbes_pings.cereal (239110a): Smudge error: Error downloading ` `utils/uw_tests/datasets/ripples/mbes_pings.cereal (239110acadad7783d3fdde1a1baffff01ff4bf769f6393bafce08048016b8f7f): ` `batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.` `Errors logged to '/home/jungdonghwi@ad.ufl.edu/Downloads/UWExploration/.git/lfs/logs/20231031T161112.663884972.log'.` `Use git lfs logs last to view the log.` `error: external filter 'git-lfs filter-process' failed` `fatal: utils/uw_tests/datasets/ripples/mbes_pings.cereal: smudge filter lfs failed` `warning: Clone succeeded, but checkout failed.` `You can inspect what was checked out with 'git status'` `and retry with 'git restore --source=HEAD :/'`
> 
> To follow the instructions in 'Basic demo with one AUV', the file `utils/uw_tests/datasets/ripples/mbes_pings.cereal` was necessary which I couldn't download
> 
> Is there any way to download the data files including 'ripples' and 'antarctica19_7'?

Hi, Did you slove this question? I meet the same issue.

**Comment by tantingfeng** [comment]
I have solved this. please see:
 https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh

**Comment by ignaciotb** [comment]
I can confirm @tantingfeng solution works.
Fork the repo normally, then follow the instructions here https://stackoverflow.com/a/68113604 and manually get the missing ripples/mbes_pings.cereal file from the downloaded zip file, and place it in your fork. 
I cannot purchase more bandwidth for this repo so this fix will have to do for now unfortunately
