### ISSUE TITLE
Is it necessary to convert pointcloud to .cereal files?

### ISSUE THREAD

**Issue by tantingfeng** [ignaciotb/UWExploration#45]
Hello, thank you for being willing to share your excellent work. I have a question to ask: if I already have pointcloud2 topics and odometry topics (without coordinate transformation), can I use your algorithm? Is it necessary to convert them to .cereal files?

Thank you once again for your assistance.

**Comment by ignaciotb** [comment]
Hi. Yes, the .cereal files contain surveying data to reply missions, but if you already have your own source of data (odom + sensor) you don't need them and you can run the algorithms in the repo directly on that data

**Comment by tantingfeng** [comment]
Thank you for your reply! I will attempt to directly use the ROSTopic data and will keep you updated on any progress.
